# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e0e83d87-deca-477a-89d8-2a4e40fd244d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e0e83d87-deca-477a-89d8-2a4e40fd244d".device = "/dev/disk/by-uuid/e0e83d87-deca-477a-89d8-2a4e40fd244d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4B34-73A6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a73fd3be-fa25-4ea5-9fd8-bf77bd0356b2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
