{config, ...}: let
  colors = config.lib.stylix.colors;
in {
  # Dynamically generate hyprtoolkit.conf from active Stylix colors
  xdg.configFile."hypr/hyprtoolkit.conf".text = ''
    # Generated by Stylix for Hyprtoolkit applications
    background = FF${colors.base00}
    base       = FF${colors.base01}
    alternate_base = FF${colors.base02}
    text       = FF${colors.base05}
    bright_text    = FF${colors.base07}
    accent         = FF${colors.base0D}
    accent_secondary = FF${colors.base0E}

    h1_size        = 18
    h2_size        = 15
    h3_size        = 13
    font_size      = 11
    small_font_size = 10
  '';
}
