name: NixOS Flake CI

on:
  push:
    branches:
      - nixos
  pull_request:
    branches:
      - nixos

jobs:
  nixos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Nix flake check
        run: nix flake check
        env:
          NIX_CONFIG: "experimental-features = nix-command flakes"

      - name: Build NixOS system
        run: nix build .#nixosConfigurations.main.config.system.build.toplevel
        env:
          NIX_CONFIG: "experimental-features = nix-command flakes"
